<?php
class RiesgosModel extends Model
{

    public function __construct()
    {
        parent::__construct();
    }

    public function insert($datos)
    {
        try {

            $conexion_bbdd = $this->db->connect();

            $query = $conexion_bbdd->prepare(
                'INSERT INTO documento_riesgos
                       (

                        IDPROYECTO,
                        IDAREA,
                        IDAREAOBSERVADA,
                        UBICACION_TAREA_AUDITADA,
                        TAREA_AUDITADA,
                        LIDER_AUDITORIA,
                        PARTICIPANTES,
                        EMPRESA,
                        FECHA,
                        FORTALEZAS_ACCIONES,
                        FECHA_CUMPLIMIENTO,
                        RESPONSABLE,

                        IDUSUARIO,

                        RIESGO11,
                        RIESGO11_COMMENTS ,
                        RIESGO12,
                        RIESGO12_COMMENTS ,
                        RIESGO13,
                        RIESGO13_COMMENTS ,
                        RIESGO14,
                        RIESGO14_COMMENTS ,
                        RIESGO15,
                        RIESGO15_COMMENTS ,
                        RIESGO16,
                        RIESGO16_COMMENTS ,
                        RIESGO17,
                        RIESGO17_COMMENTS ,
                        RIESGO21,
                        RIESGO21_COMMENTS ,
                        RIESGO22,
                        RIESGO22_COMMENTS ,
                        RIESGO23,
                        RIESGO23_COMMENTS ,
                        RIESGO24,
                        RIESGO24_COMMENTS ,
                        RIESGO25,
                        RIESGO25_COMMENTS ,
                        RIESGO26,
                        RIESGO26_COMMENTS ,
                        RIESGO27,
                        RIESGO27_COMMENTS ,
                        RIESGO28,
                        RIESGO28_COMMENTS ,
                        RIESGO31,
                        RIESGO31_COMMENTS ,
                        RIESGO32,
                        RIESGO32_COMMENTS ,
                        RIESGO33,
                        RIESGO33_COMMENTS ,
                        RIESGO34,
                        RIESGO34_COMMENTS ,
                        RIESGO35,
                        RIESGO35_COMMENTS ,
                        RIESGO36,
                        RIESGO36_COMMENTS ,
                        RIESGO37,
                        RIESGO37_COMMENTS ,
                        RIESGO38,
                        RIESGO38_COMMENTS ,
                        RIESGO39,
                        RIESGO39_COMMENTS ,
                        RIESGO310,
                        RIESGO310_COMMENTS ,
                        RIESGO41,
                        RIESGO41_COMMENTS ,
                        RIESGO42,
                        RIESGO42_COMMENTS ,
                        RIESGO43,
                        RIESGO43_COMMENTS ,
                        RIESGO44,
                        RIESGO44_COMMENTS ,
                        RIESGO45,
                        RIESGO45_COMMENTS ,
                        RIESGO46,
                        RIESGO46_COMMENTS ,
                        RIESGO47,
                        RIESGO47_COMMENTS ,
                        RIESGO48,
                        RIESGO48_COMMENTS ,
                        RIESGO49,
                        RIESGO49_COMMENTS ,
                        RIESGO410,
                        RIESGO410_COMMENTS ,
                        RIESGO411,
                        RIESGO411_COMMENTS ,
                        RIESGO412,
                        RIESGO412_COMMENTS ,
                        RIESGO51,
                        RIESGO51_COMMENTS ,
                        RIESGO52,
                        RIESGO52_COMMENTS ,
                        RIESGO53,
                        RIESGO53_COMMENTS ,
                        RIESGO54,
                        RIESGO54_COMMENTS ,
                        RIESGO55,
                        RIESGO55_COMMENTS ,
                        RIESGO56,
                        RIESGO56_COMMENTS ,
                        RIESGO57,
                        RIESGO57_COMMENTS ,
                        RIESGO61,
                        RIESGO61_COMMENTS ,
                        RIESGO62,
                        RIESGO62_COMMENTS ,
                        RIESGO63,
                        RIESGO63_COMMENTS ,
                        RIESGO64,
                        RIESGO64_COMMENTS ,
                        RIESGO65,
                        RIESGO65_COMMENTS ,
                        RIESGO66,
                        RIESGO66_COMMENTS ,
                        RIESGO67,
                        RIESGO67_COMMENTS ,
                        RIESGO68,
                        RIESGO68_COMMENTS ,
                        RIESGO69,
                        RIESGO69_COMMENTS ,
                        RIESGO610,
                        RIESGO610_COMMENTS ,
                        RIESGO611,
                        RIESGO611_COMMENTS ,
                        RIESGO612,
                        RIESGO612_COMMENTS ,
                        RIESGO71,
                        RIESGO71_COMMENTS ,
                        RIESGO72,
                        RIESGO72_COMMENTS ,
                        RIESGO73,
                        RIESGO73_COMMENTS ,
                        RIESGO74,
                        RIESGO74_COMMENTS ,
                        RIESGO75,
                        RIESGO75_COMMENTS ,
                        RIESGO76,
                        RIESGO76_COMMENTS ,
                        RIESGO77,
                        RIESGO77_COMMENTS ,
                        RIESGO78,
                        RIESGO78_COMMENTS ,
                        RIESGO79,
                        RIESGO79_COMMENTS ,
                        RIESGO710,
                        RIESGO710_COMMENTS ,
                        RIESGO711,
                        RIESGO711_COMMENTS ,
                        RIESGO81,
                        RIESGO81_COMMENTS ,
                        RIESGO82,
                        RIESGO82_COMMENTS ,
                        RIESGO83,
                        RIESGO83_COMMENTS ,
                        RIESGO84,
                        RIESGO84_COMMENTS ,
                        RIESGO85,
                        RIESGO85_COMMENTS ,
                        RIESGO86,
                        RIESGO86_COMMENTS ,
                        RIESGO87,
                        RIESGO87_COMMENTS ,
                        RIESGO88,
                        RIESGO88_COMMENTS ,
                        RIESGO89,
                        RIESGO89_COMMENTS ,
                        RIESGO810,
                        RIESGO810_COMMENTS ,
                        RIESGO91,
                        RIESGO91_COMMENTS ,
                        RIESGO92,
                        RIESGO92_COMMENTS ,
                        RIESGO93,
                        RIESGO93_COMMENTS ,
                        RIESGO94,
                        RIESGO94_COMMENTS ,
                        RIESGO95,
                        RIESGO95_COMMENTS ,
                        RIESGO96,
                        RIESGO96_COMMENTS ,
                        RIESGO97,
                        RIESGO97_COMMENTS ,
                        RIESGO98,
                        RIESGO98_COMMENTS ,
                        RIESGO99,
                        RIESGO99_COMMENTS ,
                        RIESGO101,
                        RIESGO101_COMMENTS ,
                        RIESGO102,
                        RIESGO102_COMMENTS ,
                        RIESGO103,
                        RIESGO103_COMMENTS ,
                        RIESGO104,
                        RIESGO104_COMMENTS ,
                        RIESGO105,
                        RIESGO105_COMMENTS ,
                        RIESGO111,
                        RIESGO111_COMMENTS ,
                        RIESGO112,
                        RIESGO112_COMMENTS ,
                        RIESGO113,
                        RIESGO113_COMMENTS ,
                        RIESGO114,
                        RIESGO114_COMMENTS ,
                        RIESGO115,
                        RIESGO115_COMMENTS ,
                        RIESGO116,
                        RIESGO116_COMMENTS ,
                        RIESGO117,
                        RIESGO117_COMMENTS ,
                        RIESGO118,
                        RIESGO118_COMMENTS ,
                        RIESGO121,
                        RIESGO121_COMMENTS ,
                        RIESGO122,
                        RIESGO122_COMMENTS ,
                        RIESGO123,
                        RIESGO123_COMMENTS ,
                        RIESGO124,
                        RIESGO124_COMMENTS ,
                        RIESGO125,
                        RIESGO125_COMMENTS ,
                        RIESGO131,
                        RIESGO131_COMMENTS ,
                        RIESGO132,
                        RIESGO132_COMMENTS ,
                        RIESGO133,
                        RIESGO133_COMMENTS ,
                        RIESGO134,
                        RIESGO134_COMMENTS ,
                        RIESGO135,
                        RIESGO135_COMMENTS ,
                        RIESGO136,
                        RIESGO136_COMMENTS ,
                        RIESGO137,
                        RIESGO137_COMMENTS ,
                        RIESGO138,
                        RIESGO138_COMMENTS ,
                        RIESGO141,
                        RIESGO141_COMMENTS ,
                        RIESGO142,
                        RIESGO142_COMMENTS ,
                        RIESGO143,
                        RIESGO143_COMMENTS ,
                        RIESGO144,
                        RIESGO144_COMMENTS ,
                        RIESGO145,
                        RIESGO145_COMMENTS ,
                        RIESGO146,
                        RIESGO146_COMMENTS ,
                        RIESGO147,
                        RIESGO147_COMMENTS,
                        url_pdf

                       )
                       VALUES 
                       (
                        :idProyecto,
                        :idArea,
                        :idAreaObservada,
                        :ubicacion_tarea_auditada,
                        :tarea_auditada,
                        :lider_auditoria,
                        :participantes,
                        :empresa,
                        :fecha,
                        :fortalezas_acciones,
                        :fecha_cumplimiento,
                        :responsable,

                        :idusuario,

                        :riesgo11,
                        :riesgo11_comments ,
                        :riesgo12,
                        :riesgo12_comments ,
                        :riesgo13,
                        :riesgo13_comments ,
                        :riesgo14,
                        :riesgo14_comments ,
                        :riesgo15,
                        :riesgo15_comments ,
                        :riesgo16,
                        :riesgo16_comments ,
                        :riesgo17,
                        :riesgo17_comments ,
                        :riesgo21,
                        :riesgo21_comments ,
                        :riesgo22,
                        :riesgo22_comments ,
                        :riesgo23,
                        :riesgo23_comments ,
                        :riesgo24,
                        :riesgo24_comments ,
                        :riesgo25,
                        :riesgo25_comments ,
                        :riesgo26,
                        :riesgo26_comments ,
                        :riesgo27,
                        :riesgo27_comments ,
                        :riesgo28,
                        :riesgo28_comments ,
                        :riesgo31,
                        :riesgo31_comments ,
                        :riesgo32,
                        :riesgo32_comments ,
                        :riesgo33,
                        :riesgo33_comments ,
                        :riesgo34,
                        :riesgo34_comments ,
                        :riesgo35,
                        :riesgo35_comments ,
                        :riesgo36,
                        :riesgo36_comments ,
                        :riesgo37,
                        :riesgo37_comments ,
                        :riesgo38,
                        :riesgo38_comments ,
                        :riesgo39,
                        :riesgo39_comments ,
                        :riesgo310,
                        :riesgo310_comments ,
                        :riesgo41,
                        :riesgo41_comments ,
                        :riesgo42,
                        :riesgo42_comments ,
                        :riesgo43,
                        :riesgo43_comments ,
                        :riesgo44,
                        :riesgo44_comments ,
                        :riesgo45,
                        :riesgo45_comments ,
                        :riesgo46,
                        :riesgo46_comments ,
                        :riesgo47,
                        :riesgo47_comments ,
                        :riesgo48,
                        :riesgo48_comments ,
                        :riesgo49,
                        :riesgo49_comments ,
                        :riesgo410,
                        :riesgo410_comments ,
                        :riesgo411,
                        :riesgo411_comments ,
                        :riesgo412,
                        :riesgo412_comments ,
                        :riesgo51,
                        :riesgo51_comments ,
                        :riesgo52,
                        :riesgo52_comments ,
                        :riesgo53,
                        :riesgo53_comments ,
                        :riesgo54,
                        :riesgo54_comments ,
                        :riesgo55,
                        :riesgo55_comments ,
                        :riesgo56,
                        :riesgo56_comments ,
                        :riesgo57,
                        :riesgo57_comments ,
                        :riesgo61,
                        :riesgo61_comments ,
                        :riesgo62,
                        :riesgo62_comments ,
                        :riesgo63,
                        :riesgo63_comments ,
                        :riesgo64,
                        :riesgo64_comments ,
                        :riesgo65,
                        :riesgo65_comments ,
                        :riesgo66,
                        :riesgo66_comments ,
                        :riesgo67,
                        :riesgo67_comments ,
                        :riesgo68,
                        :riesgo68_comments ,
                        :riesgo69,
                        :riesgo69_comments ,
                        :riesgo610,
                        :riesgo610_comments ,
                        :riesgo611,
                        :riesgo611_comments ,
                        :riesgo612,
                        :riesgo612_comments ,
                        :riesgo71,
                        :riesgo71_comments ,
                        :riesgo72,
                        :riesgo72_comments ,
                        :riesgo73,
                        :riesgo73_comments ,
                        :riesgo74,
                        :riesgo74_comments ,
                        :riesgo75,
                        :riesgo75_comments ,
                        :riesgo76,
                        :riesgo76_comments ,
                        :riesgo77,
                        :riesgo77_comments ,
                        :riesgo78,
                        :riesgo78_comments ,
                        :riesgo79,
                        :riesgo79_comments ,
                        :riesgo710,
                        :riesgo710_comments ,
                        :riesgo711,
                        :riesgo711_comments ,
                        :riesgo81,
                        :riesgo81_comments ,
                        :riesgo82,
                        :riesgo82_comments ,
                        :riesgo83,
                        :riesgo83_comments ,
                        :riesgo84,
                        :riesgo84_comments ,
                        :riesgo85,
                        :riesgo85_comments ,
                        :riesgo86,
                        :riesgo86_comments ,
                        :riesgo87,
                        :riesgo87_comments ,
                        :riesgo88,
                        :riesgo88_comments ,
                        :riesgo89,
                        :riesgo89_comments ,
                        :riesgo810,
                        :riesgo810_comments ,
                        :riesgo91,
                        :riesgo91_comments ,
                        :riesgo92,
                        :riesgo92_comments ,
                        :riesgo93,
                        :riesgo93_comments ,
                        :riesgo94,
                        :riesgo94_comments ,
                        :riesgo95,
                        :riesgo95_comments ,
                        :riesgo96,
                        :riesgo96_comments ,
                        :riesgo97,
                        :riesgo97_comments ,
                        :riesgo98,
                        :riesgo98_comments ,
                        :riesgo99,
                        :riesgo99_comments ,
                        :riesgo101,
                        :riesgo101_comments ,
                        :riesgo102,
                        :riesgo102_comments ,
                        :riesgo103,
                        :riesgo103_comments ,
                        :riesgo104,
                        :riesgo104_comments ,
                        :riesgo105,
                        :riesgo105_comments ,
                        :riesgo111,
                        :riesgo111_comments ,
                        :riesgo112,
                        :riesgo112_comments ,
                        :riesgo113,
                        :riesgo113_comments ,
                        :riesgo114,
                        :riesgo114_comments ,
                        :riesgo115,
                        :riesgo115_comments ,
                        :riesgo116,
                        :riesgo116_comments ,
                        :riesgo117,
                        :riesgo117_comments ,
                        :riesgo118,
                        :riesgo118_comments ,
                        :riesgo121,
                        :riesgo121_comments ,
                        :riesgo122,
                        :riesgo122_comments ,
                        :riesgo123,
                        :riesgo123_comments ,
                        :riesgo124,
                        :riesgo124_comments ,
                        :riesgo125,
                        :riesgo125_comments ,
                        :riesgo131,
                        :riesgo131_comments ,
                        :riesgo132,
                        :riesgo132_comments ,
                        :riesgo133,
                        :riesgo133_comments ,
                        :riesgo134,
                        :riesgo134_comments ,
                        :riesgo135,
                        :riesgo135_comments ,
                        :riesgo136,
                        :riesgo136_comments ,
                        :riesgo137,
                        :riesgo137_comments ,
                        :riesgo138,
                        :riesgo138_comments ,
                        :riesgo141,
                        :riesgo141_comments ,
                        :riesgo142,
                        :riesgo142_comments ,
                        :riesgo143,
                        :riesgo143_comments ,
                        :riesgo144,
                        :riesgo144_comments ,
                        :riesgo145,
                        :riesgo145_comments ,
                        :riesgo146,
                        :riesgo146_comments ,
                        :riesgo147,
                        :riesgo147_comments,
                        :url_pdf



                       )
                       
                       '


            );

            $query->execute([


                'idProyecto' => $datos['idProyecto'],
                'idArea' => $datos['idArea'],
                'idAreaObservada' => $datos['idAreaObservada'],
                "ubicacion_tarea_auditada" =>  $datos["ubicacion_tarea_auditada"],
                "tarea_auditada" =>  $datos["tarea_auditada"],
                "lider_auditoria" =>  $datos["lider_auditoria"],
                "participantes" =>  $datos["participantes"],
                "empresa" =>  $datos["empresa"],
                "fecha" =>  $datos["fecha"],
                "fortalezas_acciones" =>  $datos["fortalezas_acciones"],
                "fecha_cumplimiento" =>  $datos["fecha_cumplimiento"],
                "responsable" =>  $datos["responsable"],
                "idusuario" =>  $datos["idusuario"],


                "riesgo11" =>  $datos["riesgo11"],
                "riesgo11_comments" => $datos["riesgo11_comments"],
                "riesgo12" =>  $datos["riesgo12"],
                "riesgo12_comments" => $datos["riesgo12_comments"],
                "riesgo13" =>  $datos["riesgo13"],
                "riesgo13_comments" => $datos["riesgo13_comments"],
                "riesgo14" =>  $datos["riesgo14"],
                "riesgo14_comments" => $datos["riesgo14_comments"],
                "riesgo15" =>  $datos["riesgo15"],
                "riesgo15_comments" => $datos["riesgo15_comments"],
                "riesgo16" =>  $datos["riesgo16"],
                "riesgo16_comments" => $datos["riesgo16_comments"],
                "riesgo17" =>  $datos["riesgo17"],
                "riesgo17_comments" => $datos["riesgo17_comments"],
                "riesgo21" =>  $datos["riesgo21"],
                "riesgo21_comments" => $datos["riesgo21_comments"],
                "riesgo22" =>  $datos["riesgo22"],
                "riesgo22_comments" => $datos["riesgo22_comments"],
                "riesgo23" =>  $datos["riesgo23"],
                "riesgo23_comments" => $datos["riesgo23_comments"],
                "riesgo24" =>  $datos["riesgo24"],
                "riesgo24_comments" => $datos["riesgo24_comments"],
                "riesgo25" =>  $datos["riesgo25"],
                "riesgo25_comments" => $datos["riesgo25_comments"],
                "riesgo26" =>  $datos["riesgo26"],
                "riesgo26_comments" => $datos["riesgo26_comments"],
                "riesgo27" =>  $datos["riesgo27"],
                "riesgo27_comments" => $datos["riesgo27_comments"],
                "riesgo28" =>  $datos["riesgo28"],
                "riesgo28_comments" => $datos["riesgo28_comments"],
                "riesgo31" =>  $datos["riesgo31"],
                "riesgo31_comments" => $datos["riesgo31_comments"],
                "riesgo32" =>  $datos["riesgo32"],
                "riesgo32_comments" => $datos["riesgo32_comments"],
                "riesgo33" =>  $datos["riesgo33"],
                "riesgo33_comments" => $datos["riesgo33_comments"],
                "riesgo34" =>  $datos["riesgo34"],
                "riesgo34_comments" => $datos["riesgo34_comments"],
                "riesgo35" =>  $datos["riesgo35"],
                "riesgo35_comments" => $datos["riesgo35_comments"],
                "riesgo36" =>  $datos["riesgo36"],
                "riesgo36_comments" => $datos["riesgo36_comments"],
                "riesgo37" =>  $datos["riesgo37"],
                "riesgo37_comments" => $datos["riesgo37_comments"],
                "riesgo38" =>  $datos["riesgo38"],
                "riesgo38_comments" => $datos["riesgo38_comments"],
                "riesgo39" =>  $datos["riesgo39"],
                "riesgo39_comments" => $datos["riesgo39_comments"],
                "riesgo310" =>  $datos["riesgo310"],
                "riesgo310_comments" => $datos["riesgo310_comments"],
                "riesgo41" =>  $datos["riesgo41"],
                "riesgo41_comments" => $datos["riesgo41_comments"],
                "riesgo42" =>  $datos["riesgo42"],
                "riesgo42_comments" => $datos["riesgo42_comments"],
                "riesgo43" =>  $datos["riesgo43"],
                "riesgo43_comments" => $datos["riesgo43_comments"],
                "riesgo44" =>  $datos["riesgo44"],
                "riesgo44_comments" => $datos["riesgo44_comments"],
                "riesgo45" =>  $datos["riesgo45"],
                "riesgo45_comments" => $datos["riesgo45_comments"],
                "riesgo46" =>  $datos["riesgo46"],
                "riesgo46_comments" => $datos["riesgo46_comments"],
                "riesgo47" =>  $datos["riesgo47"],
                "riesgo47_comments" => $datos["riesgo47_comments"],
                "riesgo48" =>  $datos["riesgo48"],
                "riesgo48_comments" => $datos["riesgo48_comments"],
                "riesgo49" =>  $datos["riesgo49"],
                "riesgo49_comments" => $datos["riesgo49_comments"],
                "riesgo410" =>  $datos["riesgo410"],
                "riesgo410_comments" => $datos["riesgo410_comments"],
                "riesgo411" =>  $datos["riesgo411"],
                "riesgo411_comments" => $datos["riesgo411_comments"],
                "riesgo412" =>  $datos["riesgo412"],
                "riesgo412_comments" => $datos["riesgo412_comments"],
                "riesgo51" =>  $datos["riesgo51"],
                "riesgo51_comments" => $datos["riesgo51_comments"],
                "riesgo52" =>  $datos["riesgo52"],
                "riesgo52_comments" => $datos["riesgo52_comments"],
                "riesgo53" =>  $datos["riesgo53"],
                "riesgo53_comments" => $datos["riesgo53_comments"],
                "riesgo54" =>  $datos["riesgo54"],
                "riesgo54_comments" => $datos["riesgo54_comments"],
                "riesgo55" =>  $datos["riesgo55"],
                "riesgo55_comments" => $datos["riesgo55_comments"],
                "riesgo56" =>  $datos["riesgo56"],
                "riesgo56_comments" => $datos["riesgo56_comments"],
                "riesgo57" =>  $datos["riesgo57"],
                "riesgo57_comments" => $datos["riesgo57_comments"],
                "riesgo61" =>  $datos["riesgo61"],
                "riesgo61_comments" => $datos["riesgo61_comments"],
                "riesgo62" =>  $datos["riesgo62"],
                "riesgo62_comments" => $datos["riesgo62_comments"],
                "riesgo63" =>  $datos["riesgo63"],
                "riesgo63_comments" => $datos["riesgo63_comments"],
                "riesgo64" =>  $datos["riesgo64"],
                "riesgo64_comments" => $datos["riesgo64_comments"],
                "riesgo65" =>  $datos["riesgo65"],
                "riesgo65_comments" => $datos["riesgo65_comments"],
                "riesgo66" =>  $datos["riesgo66"],
                "riesgo66_comments" => $datos["riesgo66_comments"],
                "riesgo67" =>  $datos["riesgo67"],
                "riesgo67_comments" => $datos["riesgo67_comments"],
                "riesgo68" =>  $datos["riesgo68"],
                "riesgo68_comments" => $datos["riesgo68_comments"],
                "riesgo69" =>  $datos["riesgo69"],
                "riesgo69_comments" => $datos["riesgo69_comments"],
                "riesgo610" =>  $datos["riesgo610"],
                "riesgo610_comments" => $datos["riesgo610_comments"],
                "riesgo611" =>  $datos["riesgo611"],
                "riesgo611_comments" => $datos["riesgo611_comments"],
                "riesgo612" =>  $datos["riesgo612"],
                "riesgo612_comments" => $datos["riesgo612_comments"],
                "riesgo71" =>  $datos["riesgo71"],
                "riesgo71_comments" => $datos["riesgo71_comments"],
                "riesgo72" =>  $datos["riesgo72"],
                "riesgo72_comments" => $datos["riesgo72_comments"],
                "riesgo73" =>  $datos["riesgo73"],
                "riesgo73_comments" => $datos["riesgo73_comments"],
                "riesgo74" =>  $datos["riesgo74"],
                "riesgo74_comments" => $datos["riesgo74_comments"],
                "riesgo75" =>  $datos["riesgo75"],
                "riesgo75_comments" => $datos["riesgo75_comments"],
                "riesgo76" =>  $datos["riesgo76"],
                "riesgo76_comments" => $datos["riesgo76_comments"],
                "riesgo77" =>  $datos["riesgo77"],
                "riesgo77_comments" => $datos["riesgo77_comments"],
                "riesgo78" =>  $datos["riesgo78"],
                "riesgo78_comments" => $datos["riesgo78_comments"],
                "riesgo79" =>  $datos["riesgo79"],
                "riesgo79_comments" => $datos["riesgo79_comments"],
                "riesgo710" =>  $datos["riesgo710"],
                "riesgo710_comments" => $datos["riesgo710_comments"],
                "riesgo711" =>  $datos["riesgo711"],
                "riesgo711_comments" => $datos["riesgo711_comments"],
                "riesgo81" =>  $datos["riesgo81"],
                "riesgo81_comments" => $datos["riesgo81_comments"],
                "riesgo82" =>  $datos["riesgo82"],
                "riesgo82_comments" => $datos["riesgo82_comments"],
                "riesgo83" =>  $datos["riesgo83"],
                "riesgo83_comments" => $datos["riesgo83_comments"],
                "riesgo84" =>  $datos["riesgo84"],
                "riesgo84_comments" => $datos["riesgo84_comments"],
                "riesgo85" =>  $datos["riesgo85"],
                "riesgo85_comments" => $datos["riesgo85_comments"],
                "riesgo86" =>  $datos["riesgo86"],
                "riesgo86_comments" => $datos["riesgo86_comments"],
                "riesgo87" =>  $datos["riesgo87"],
                "riesgo87_comments" => $datos["riesgo87_comments"],
                "riesgo88" =>  $datos["riesgo88"],
                "riesgo88_comments" => $datos["riesgo88_comments"],
                "riesgo89" =>  $datos["riesgo89"],
                "riesgo89_comments" => $datos["riesgo89_comments"],
                "riesgo810" =>  $datos["riesgo810"],
                "riesgo810_comments" => $datos["riesgo810_comments"],
                "riesgo91" =>  $datos["riesgo91"],
                "riesgo91_comments" => $datos["riesgo91_comments"],
                "riesgo92" =>  $datos["riesgo92"],
                "riesgo92_comments" => $datos["riesgo92_comments"],
                "riesgo93" =>  $datos["riesgo93"],
                "riesgo93_comments" => $datos["riesgo93_comments"],
                "riesgo94" =>  $datos["riesgo94"],
                "riesgo94_comments" => $datos["riesgo94_comments"],
                "riesgo95" =>  $datos["riesgo95"],
                "riesgo95_comments" => $datos["riesgo95_comments"],
                "riesgo96" =>  $datos["riesgo96"],
                "riesgo96_comments" => $datos["riesgo96_comments"],
                "riesgo97" =>  $datos["riesgo97"],
                "riesgo97_comments" => $datos["riesgo97_comments"],
                "riesgo98" =>  $datos["riesgo98"],
                "riesgo98_comments" => $datos["riesgo98_comments"],
                "riesgo99" =>  $datos["riesgo99"],
                "riesgo99_comments" => $datos["riesgo99_comments"],
                "riesgo101" =>  $datos["riesgo101"],
                "riesgo101_comments" => $datos["riesgo101_comments"],
                "riesgo102" =>  $datos["riesgo102"],
                "riesgo102_comments" => $datos["riesgo102_comments"],
                "riesgo103" =>  $datos["riesgo103"],
                "riesgo103_comments" => $datos["riesgo103_comments"],
                "riesgo104" =>  $datos["riesgo104"],
                "riesgo104_comments" => $datos["riesgo104_comments"],
                "riesgo105" =>  $datos["riesgo105"],
                "riesgo105_comments" => $datos["riesgo105_comments"],
                "riesgo111" =>  $datos["riesgo111"],
                "riesgo111_comments" => $datos["riesgo111_comments"],
                "riesgo112" =>  $datos["riesgo112"],
                "riesgo112_comments" => $datos["riesgo112_comments"],
                "riesgo113" =>  $datos["riesgo113"],
                "riesgo113_comments" => $datos["riesgo113_comments"],
                "riesgo114" =>  $datos["riesgo114"],
                "riesgo114_comments" => $datos["riesgo114_comments"],
                "riesgo115" =>  $datos["riesgo115"],
                "riesgo115_comments" => $datos["riesgo115_comments"],
                "riesgo116" =>  $datos["riesgo116"],
                "riesgo116_comments" => $datos["riesgo116_comments"],
                "riesgo117" =>  $datos["riesgo117"],
                "riesgo117_comments" => $datos["riesgo117_comments"],
                "riesgo118" =>  $datos["riesgo118"],
                "riesgo118_comments" => $datos["riesgo118_comments"],
                "riesgo121" =>  $datos["riesgo121"],
                "riesgo121_comments" => $datos["riesgo121_comments"],
                "riesgo122" =>  $datos["riesgo122"],
                "riesgo122_comments" => $datos["riesgo122_comments"],
                "riesgo123" =>  $datos["riesgo123"],
                "riesgo123_comments" => $datos["riesgo123_comments"],
                "riesgo124" =>  $datos["riesgo124"],
                "riesgo124_comments" => $datos["riesgo124_comments"],
                "riesgo125" =>  $datos["riesgo125"],
                "riesgo125_comments" => $datos["riesgo125_comments"],
                "riesgo131" =>  $datos["riesgo131"],
                "riesgo131_comments" => $datos["riesgo131_comments"],
                "riesgo132" =>  $datos["riesgo132"],
                "riesgo132_comments" => $datos["riesgo132_comments"],
                "riesgo133" =>  $datos["riesgo133"],
                "riesgo133_comments" => $datos["riesgo133_comments"],
                "riesgo134" =>  $datos["riesgo134"],
                "riesgo134_comments" => $datos["riesgo134_comments"],
                "riesgo135" =>  $datos["riesgo135"],
                "riesgo135_comments" => $datos["riesgo135_comments"],
                "riesgo136" =>  $datos["riesgo136"],
                "riesgo136_comments" => $datos["riesgo136_comments"],
                "riesgo137" =>  $datos["riesgo137"],
                "riesgo137_comments" => $datos["riesgo137_comments"],
                "riesgo138" =>  $datos["riesgo138"],
                "riesgo138_comments" => $datos["riesgo138_comments"],
                "riesgo141" =>  $datos["riesgo141"],
                "riesgo141_comments" => $datos["riesgo141_comments"],
                "riesgo142" =>  $datos["riesgo142"],
                "riesgo142_comments" => $datos["riesgo142_comments"],
                "riesgo143" =>  $datos["riesgo143"],
                "riesgo143_comments" => $datos["riesgo143_comments"],
                "riesgo144" =>  $datos["riesgo144"],
                "riesgo144_comments" => $datos["riesgo144_comments"],
                "riesgo145" =>  $datos["riesgo145"],
                "riesgo145_comments" => $datos["riesgo145_comments"],
                "riesgo146" =>  $datos["riesgo146"],
                "riesgo146_comments" => $datos["riesgo146_comments"],
                "riesgo147" =>  $datos["riesgo147"],
                "riesgo147_comments" => $datos["riesgo147_comments"],
                "url_pdf" => '',



            ]);
            
            
            $last_insert_id = $conexion_bbdd->lastInsertId();

            return $last_insert_id;

        } catch (PDOException $e) {
            echo $e->getMessage();
            return null;
        }
    }

    public function findByIdRiesgo($idRiesgo)
    {


        $rowOpt = array();

        $query = $this->db->connect()->prepare("SELECT	id,
        usuario_nombres,
        usuario_apellidos,
        proyecto_nombre,
        area_nombre,
        area_observada_nombre,
        ubicacion,
        tarea_auditada ,
        lider_auditoria,
        participantes,
        empresa,
        fecha ,
        riesgo11 , 
        riesgo11_comments , 
        riesgo12 , 
        riesgo12_comments , 
        riesgo13 , 
        riesgo13_comments , 
        riesgo14 , 
        riesgo14_comments , 
        riesgo15 , 
        riesgo15_comments , 
        riesgo16 , 
        riesgo16_comments , 
        riesgo17 , 
        riesgo17_comments , 
        riesgo21 , 
        riesgo21_comments , 
        riesgo22 , 
        riesgo22_comments , 
        riesgo23 , 
        riesgo23_comments , 
        riesgo24 , 
        riesgo24_comments , 
        riesgo25 , 
        riesgo25_comments , 
        riesgo26 , 
        riesgo26_comments , 
        riesgo27 , 
        riesgo27_comments , 
        riesgo28 , 
        riesgo28_comments , 
        riesgo31 , 
        riesgo31_comments , 
        riesgo32 , 
        riesgo32_comments , 
        riesgo33 , 
        riesgo33_comments , 
        riesgo34 , 
        riesgo34_comments , 
        riesgo35 , 
        riesgo35_comments , 
        riesgo36 , 
        riesgo36_comments , 
        riesgo37 , 
        riesgo37_comments , 
        riesgo38 , 
        riesgo38_comments , 
        riesgo39 , 
        riesgo39_comments , 
        riesgo310 , 
        riesgo310_comments , 
        riesgo41 , 
        riesgo41_comments , 
        riesgo42 , 
        riesgo42_comments , 
        riesgo43 , 
        riesgo43_comments , 
        riesgo44 , 
        riesgo44_comments , 
        riesgo45 , 
        riesgo45_comments , 
        riesgo46 , 
        riesgo46_comments , 
        riesgo47 , 
        riesgo47_comments , 
        riesgo48 , 
        riesgo48_comments , 
        riesgo49 , 
        riesgo49_comments , 
        riesgo410 , 
        riesgo410_comments , 
        riesgo411 , 
        riesgo411_comments , 
        riesgo412 , 
        riesgo412_comments , 
        riesgo51 , 
        riesgo51_comments , 
        riesgo52 , 
        riesgo52_comments , 
        riesgo53 , 
        riesgo53_comments , 
        riesgo54 , 
        riesgo54_comments , 
        riesgo55 , 
        riesgo55_comments , 
        riesgo56 , 
        riesgo56_comments , 
        riesgo57 , 
        riesgo57_comments , 
        riesgo61 , 
        riesgo61_comments , 
        riesgo62 , 
        riesgo62_comments , 
        riesgo63 , 
        riesgo63_comments , 
        riesgo64 , 
        riesgo64_comments , 
        riesgo65 , 
        riesgo65_comments , 
        riesgo66 , 
        riesgo66_comments , 
        riesgo67 , 
        riesgo67_comments , 
        riesgo68 , 
        riesgo68_comments , 
        riesgo69 , 
        riesgo69_comments , 
        riesgo610 , 
        riesgo610_comments , 
        riesgo611 , 
        riesgo611_comments , 
        riesgo612 , 
        riesgo612_comments , 
        riesgo71 , 
        riesgo71_comments , 
        riesgo72 , 
        riesgo72_comments , 
        riesgo73 , 
        riesgo73_comments , 
        riesgo74 , 
        riesgo74_comments , 
        riesgo75 , 
        riesgo75_comments , 
        riesgo76 , 
        riesgo76_comments , 
        riesgo77 , 
        riesgo77_comments , 
        riesgo78 , 
        riesgo78_comments , 
        riesgo79 , 
        riesgo79_comments , 
        riesgo710 , 
        riesgo710_comments , 
        riesgo711 , 
        riesgo711_comments , 
        riesgo81 , 
        riesgo81_comments , 
        riesgo82 , 
        riesgo82_comments , 
        riesgo83 , 
        riesgo83_comments , 
        riesgo84 , 
        riesgo84_comments , 
        riesgo85 , 
        riesgo85_comments , 
        riesgo86 , 
        riesgo86_comments , 
        riesgo87 , 
        riesgo87_comments , 
        riesgo88 , 
        riesgo88_comments , 
        riesgo89 , 
        riesgo89_comments , 
        riesgo810 , 
        riesgo810_comments , 
        riesgo91 , 
        riesgo91_comments , 
        riesgo92 , 
        riesgo92_comments , 
        riesgo93 , 
        riesgo93_comments , 
        riesgo94 , 
        riesgo94_comments , 
        riesgo95 , 
        riesgo95_comments , 
        riesgo96 , 
        riesgo96_comments , 
        riesgo97 , 
        riesgo97_comments , 
        riesgo98 , 
        riesgo98_comments , 
        riesgo99 , 
        riesgo99_comments , 
        riesgo101 , 
        riesgo101_comments , 
        riesgo102 , 
        riesgo102_comments , 
        riesgo103 , 
        riesgo103_comments , 
        riesgo104 , 
        riesgo104_comments , 
        riesgo105 , 
        riesgo105_comments , 
        riesgo111 , 
        riesgo111_comments , 
        riesgo112 , 
        riesgo112_comments , 
        riesgo113 , 
        riesgo113_comments , 
        riesgo114 , 
        riesgo114_comments , 
        riesgo115 , 
        riesgo115_comments , 
        riesgo116 , 
        riesgo116_comments , 
        riesgo117 , 
        riesgo117_comments , 
        riesgo118 , 
        riesgo118_comments , 
        riesgo121 , 
        riesgo121_comments , 
        riesgo122 , 
        riesgo122_comments , 
        riesgo123 , 
        riesgo123_comments , 
        riesgo124 , 
        riesgo124_comments , 
        riesgo125 , 
        riesgo125_comments , 
        riesgo131 , 
        riesgo131_comments , 
        riesgo132 , 
        riesgo132_comments , 
        riesgo133 , 
        riesgo133_comments , 
        riesgo134 , 
        riesgo134_comments , 
        riesgo135 , 
        riesgo135_comments , 
        riesgo136 , 
        riesgo136_comments , 
        riesgo137 , 
        riesgo137_comments , 
        riesgo138 , 
        riesgo138_comments , 
        riesgo141 , 
        riesgo141_comments , 
        riesgo142 , 
        riesgo142_comments , 
        riesgo143 , 
        riesgo143_comments , 
        riesgo144 , 
        riesgo144_comments , 
        riesgo145 , 
        riesgo145_comments , 
        riesgo146 , 
        riesgo146_comments , 
        riesgo147 , 
        riesgo147_comments ,
        fortalezas_acciones,
        fecha_cumplimiento,
        responsable,
        registro FROM  view_documento_riesgo WHERE id ='$idRiesgo' ");
        try {

            $query->execute();

            while ($row = $query->fetch()) {
                $rowOpt = $row;
            }

            return $rowOpt;
        } catch (PDOException $e) {
            return [];
        }
    }


    public function actualizarUrlPdfRiesgo($idRiesgo, $urlPdf)
    {

        $query = $this->db->connect()->prepare("UPDATE documento_riesgos SET url_pdf = :url_pdf WHERE id = :id ");

        try {

            $query->execute(['url_pdf'  => $urlPdf, 'id' => $idRiesgo]);

            return true;
        } catch (PDOException $e) {
            return $e->intl_get_error_message;
        }
    }

    public function getUrlPdf($id)
    {
        $url_foto = [];

        $query = $this->db->connect()->prepare('SELECT url_pdf FROM documento_riesgos WHERE id = :id ');

        $query->execute(['id' => $id]);

        try {

            while ($rs = $query->fetch()) {

                $url_foto = $rs;
            }

            return $url_foto;

        } catch (PDOException $e) {
            return [];
        }
    }

}
